AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
Layout/ArrayAlignment:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  Enabled: true
Layout/LineLength:
  Max: 100
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true

Metrics/MethodLength:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
  Max: 125
Metrics/ModuleLength:
  Max: 125
Metrics/ParameterLists:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/AbcSize:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Style/AndOr:
  Enabled: true
Style/ClassCheck:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GuardClause:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/HashTransformKeys:
  Enabled: false

Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
